// let currentlevel;

function initLevel5() {

    currentlevel = new Level(
        [
            new Orc2(),
            new Orc2(),
            new Orc2(),
            new Orc3(),
            new Orc3(),
            new Orc2(),
            new Orc2(),
            new Orc2(),
            new Orc3(),
            new Orc3(),
            new Orc2(),
            new Orc2(),
            new Orc2(),
            new Orc3(),
            new Orc3(),
        ], [
            new Endboss(),
            new Endboss(),
            new Endboss(),
            new Endboss2(),
            new Endboss2(),
            new Endboss2(),
            new Endboss3(),
            new Endboss3(),
            new Endboss3(),
            new Endboss3(),
        ], [
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', -1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', -1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', -1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', -1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', -1279.995, -240),

            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', 0, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', 0, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', 0, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', 0, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', 0, -240),

            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', 1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', 1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', 1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', 1279.995, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', 1279.995, -240),

            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', 2559.99, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', 2559.99, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', 2559.99, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', 2559.99, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', 2559.99, -240),

            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', 3839.85, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', 3839.85, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', 3839.85, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', 3839.85, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', 3839.985, -240),

            new BackgroundObject2('img/bg/PNG/game_background_6/layers/battleground.png', 5119.98, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_land.png', 5119.98, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/ground_decor.png', 5119.98, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/back_decor.png', 5119.98, 0),
            new BackgroundObject2('img/bg/PNG/game_background_6/layers/front_decor.png', 5119.98, -240),
        ], [
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
            new Potion2(),
        ], [
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
            new Spellbook(),
        ]
    );
}